services:
  frontend:
    image: ghcr.io/cxconrad/climatelens_ui:latest
    ports:
      - target: 4173
        published: 4173
        protocol: tcp
        mode: host
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    restart: unless-stopped

  app:
    # build: .
    image: ghcr.io/fumizwerg/climatelens-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      restart_policy:
        condition: on-failure
    restart: unless-stopped